# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('attachfile', models.CharField(max_length=254)),
                ('mailid', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
