# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151211_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 11, 12, 55, 32, 684493, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
