# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mail_updatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='text',
            new_name='content',
        ),
    ]
