# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151211_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachfile', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='mail',
            name='attachfile',
        ),
        migrations.AddField(
            model_name='attachfile',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Mail'),
        ),
    ]
