# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20151212_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfile',
            name='attachfile',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
