# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20151212_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='timestamp',
            field=models.CharField(max_length=254),
        ),
    ]
