# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20151212_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachfile',
            name='filename',
            field=models.CharField(default=datetime.datetime(2015, 12, 16, 15, 16, 14, 46485), max_length=254),
            preserve_default=False,
        ),
    ]
