# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='mail',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2015, 12, 16, 16, 22, 23, 293202), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
