# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20151216_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='slug',
        ),
    ]
