# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_mail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachfile',
            name='filesize',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
