# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_attachfile_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachfile',
            name='filesize',
            field=models.CharField(default=datetime.datetime(2015, 12, 18, 21, 24, 43, 811554), max_length=150),
            preserve_default=False,
        ),
    ]
