# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_attachfile_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfile',
            name='filesize',
            field=models.IntegerField(),
        ),
    ]
