# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20151218_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfile',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
