# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20151218_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachfile',
            old_name='filesize',
            new_name='file_size',
        ),
    ]
