# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20151218_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachfile',
            name='filesize',
        ),
    ]
