# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20151218_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={},
        ),
        migrations.RemoveField(
            model_name='mail',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='updatetime',
        ),
    ]
