# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20151218_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=-1)),
                ('user_ip', models.CharField(max_length=150, null=True)),
                ('user_content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AddField(
            model_name='mail',
            name='attach_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mail',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Mail'),
        ),
    ]
