# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_comments_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
