# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_comments_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='fromperson_re',
            field=models.CharField(default=datetime.datetime(2016, 1, 3, 22, 33, 23, 538219), max_length=150),
            preserve_default=False,
        ),
    ]
